apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-database-service"
spec:
  selector:
    app: "{{ .Release.Name }}-database-sfs"
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
