apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: "{{ .Release.Name }}-frontend-rollout"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-frontend"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-frontend"
    spec:
      containers:
        - name: "{{ .Release.Name }}-frontend"
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: "{{ .Values.frontend.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
  strategy:
    blueGreen:
      activeService: "{{ .Release.Name }}-frontend-service-active"
      previewService: "{{ .Release.Name }}-frontend-service-preview"
      autoPromotionEnabled: true
