apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-backend-service-active"
spec:
  selector:
    app: "{{ .Release.Name }}-backend"
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.backend.containerPort }}
