apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-backend-service"
spec:
  selector:
    app: hori-backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 33000
