apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-pvc-database"
spec:
  storageClassName: "{{ .Release.Name }}-nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
