apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-database-sfs"
spec:
  serviceName: "{{ .Release.Name }}-database-sfs"
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-database-sfs"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-database-sfs"
    spec:
      containers:
        - name: "{{ .Release.Name }}-database-sfs"
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: api
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: "{{ .Release.Name }}-pv-database"
              mountPath: "/var/lib/postgresql/data/"
      volumes:
        - name: "{{ .Release.Name }}-pv-database"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-pvc-database"
